import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { motion } from "framer-motion-3d";
export function Office(props) {
  const { section } = props;
  const { nodes, materials } = useGLTF("models/CV_room1.gltf");
  return (
    <group {...props} dispose={null}>
      <motion.group
        position={[-0.017, 0.474, -2.304]}
        rotation={[-Math.PI, 0.036, -Math.PI]}
        scale={0.064}
        animate={{
          scale: section === 0 ? 0.064 : 0,
        }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Node-Mesh"].geometry}
          material={materials.Executive}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Node-Mesh_1"].geometry}
          material={materials.Executive__1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Node-Mesh_2"].geometry}
          material={materials.Executive__2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Node-Mesh_3"].geometry}
          material={materials.Executive__3}
        />
      </motion.group>
      <motion.mesh
        castShadow
        receiveShadow
        geometry={nodes.Houseplant_mesh.geometry}
        material={materials.Houseplant_mat1}
        position={[3.687, -0.102, -3.98]}
        scale={0.385}
        animate={{
          scale: section === 0 ? 0.385 : 0,
        }}
      />
      <motion.mesh
        castShadow
        receiveShadow
        geometry={nodes.Rug.geometry}
        material={materials.Mat}
        position={[0, -0.063, 2.057]}
        scale={-0.046}
        animate={{
          scale: section === 0 ? -0.046 : 0,
        }}
      />
      <group position={[0.036, -0.08, 0.017]} scale={5.016}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plan_1.geometry}
          material={materials.Floor}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plan_2.geometry}
          material={materials.Default}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plan_3.geometry}
          material={materials.Walls}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plan001.geometry}
        material={nodes.Plan001.material}
        position={[0.036, -0.08, 0.017]}
        scale={5.016}
      />
      <group
        position={[1.478, 1.677, -4.396]}
        rotation={[-Math.PI / 2, 0, -0.392]}
        scale={2.261}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Calendar-8GqQAqxi3qk_1"].geometry}
          material={materials.Calendar_Texture}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Calendar-8GqQAqxi3qk_2"].geometry}
          material={materials.Calendar_Aquamarine}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Calendar-8GqQAqxi3qk_3"].geometry}
          material={materials.Calendar_Ivory}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Calendar-8GqQAqxi3qk_4"].geometry}
          material={materials.FrontColor}
        />
      </group>
      <motion.group
        position={[0.304, -0.036, -4.104]}
        rotation={[-Math.PI / 2, 0, -1.575]}
        scale={181.899}
        animate={{
          scale: section === 0 ? 181.899 : 0,
        }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Desk_1.geometry}
          material={materials.BlackCoatSteel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Desk_2.geometry}
          material={materials.GrayPlastic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Desk_3.geometry}
          material={materials.WhiteSteelScrew}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Desk_4.geometry}
          material={materials.BlackPlastic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Desk_5.geometry}
          material={materials.BlackWood}
        />
      </motion.group>
      <motion.group
        position={[0.008, 2.437, -4.093]}
        rotation={[-Math.PI / 2, 0, 3.138]}
        scale={54.915}
        animate={{
          scale: section === 0 ? 54.915 : 0,
        }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["Dual_Monitors_on_sit-stand_arm|group112678593|Dupli|5"]
              .geometry
          }
          material={materials["mat22.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["Dual_Monitors_on_sit-stand_arm|group1219313228|Dupli|2"]
              .geometry
          }
          material={materials["mat22.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["Dual_Monitors_on_sit-stand_arm|group1462626064|Dupli|7"]
              .geometry
          }
          material={materials["mat22.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["Dual_Monitors_on_sit-stand_arm|group1658787459|Dupli|18"]
              .geometry
          }
          material={materials["mat22.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["Dual_Monitors_on_sit-stand_arm|group1698824667|Dupli|12"]
              .geometry
          }
          material={materials["mat22.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["Dual_Monitors_on_sit-stand_arm|group1746518091|Dupli|8"]
              .geometry
          }
          material={materials["mat23.015"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["Dual_Monitors_on_sit-stand_arm|group1783798096|Dupli|3"]
              .geometry
          }
          material={materials["mat23.015"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["Dual_Monitors_on_sit-stand_arm|group1896072715|Dupli|19"]
              .geometry
          }
          material={materials["mat22.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["Dual_Monitors_on_sit-stand_arm|group2060347243|Dupli|9"]
              .geometry
          }
          material={materials["mat22.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["Dual_Monitors_on_sit-stand_arm|group2063576334|Dupli|11"]
              .geometry
          }
          material={materials["mat22.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["Dual_Monitors_on_sit-stand_arm|group2070617275|Dupli|13"]
              .geometry
          }
          material={materials["mat23.015"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["Dual_Monitors_on_sit-stand_arm|group2128326706|Dupli|16"]
              .geometry
          }
          material={materials["mat23.015"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["Dual_Monitors_on_sit-stand_arm|group451364077|Dupli|20"]
              .geometry
          }
          material={materials["mat22.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["Dual_Monitors_on_sit-stand_arm|group575146565|Dupli|6"]
              .geometry
          }
          material={materials["mat22.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["Dual_Monitors_on_sit-stand_arm|group625259463|Dupli|4"]
              .geometry
          }
          material={materials["mat23.015"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["Dual_Monitors_on_sit-stand_arm|group710626981|Dupli|14"]
              .geometry
          }
          material={materials["mat22.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["Dual_Monitors_on_sit-stand_arm|group786212531|Dupli|21"]
              .geometry
          }
          material={materials["mat22.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["Dual_Monitors_on_sit-stand_arm|group929043094|Dupli|10"]
              .geometry
          }
          material={materials["mat22.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["Dual_Monitors_on_sit-stand_arm|group974294459|Dupli|17"]
              .geometry
          }
          material={materials["mat23.015"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["Dual_Monitors_on_sit-stand_arm|group150401702|Dupli|15_1"]
              .geometry
          }
          material={materials["mat22.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["Dual_Monitors_on_sit-stand_arm|group150401702|Dupli|15_2"]
              .geometry
          }
          material={materials["mat23.015"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["Dual_Monitors_on_sit-stand_arm|group1691283673|Dupli|23_1"]
              .geometry
          }
          material={materials["mat22.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["Dual_Monitors_on_sit-stand_arm|group1691283673|Dupli|23_2"]
              .geometry
          }
          material={materials["mat23.015"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["Dual_Monitors_on_sit-stand_arm|group1691283673|Dupli|23_3"]
              .geometry
          }
          material={materials["mat21.012"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["Dual_Monitors_on_sit-stand_arm|group329542522|Dupli|_1"]
              .geometry
          }
          material={materials["mat22.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["Dual_Monitors_on_sit-stand_arm|group329542522|Dupli|_2"]
              .geometry
          }
          material={materials["mat23.015"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["Dual_Monitors_on_sit-stand_arm|group576947092|Dupli|1_1"]
              .geometry
          }
          material={materials["mat22.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["Dual_Monitors_on_sit-stand_arm|group576947092|Dupli|1_2"]
              .geometry
          }
          material={materials["mat23.015"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["Dual_Monitors_on_sit-stand_arm|group860618825|Dupli|22_1"]
              .geometry
          }
          material={materials["mat22.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["Dual_Monitors_on_sit-stand_arm|group860618825|Dupli|22_2"]
              .geometry
          }
          material={materials["mat23.015"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["Dual_Monitors_on_sit-stand_arm|group860618825|Dupli|22_3"]
              .geometry
          }
          material={materials["mat21.012"]}
        />
      </motion.group>
      <group
        position={[-0.011, 2.176, -3.424]}
        rotation={[-1.565, 0.001, -0.044]}
        scale={37.32}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group1030983910|Dupli|22"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group1075691498|Dupli|58"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group1149852049|Dupli|53"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group1152190519|Dupli|19"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group1180881246|Dupli|50"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group1238060299|Dupli|28"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group1238428394|Dupli|61"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group1272091893|Dupli|35"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group1316349499|Dupli|39"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group1323238240|Dupli|32"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group145618305|Dupli|23"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group1486350934|Dupli|63"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group150579309|Dupli|11"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group1529968652|Dupli|6"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group1571332333|Dupli|33"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group1581414308|Dupli|8"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group1589752359|Dupli|26"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group1629393722|Dupli|64"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group1629609685|Dupli|21"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group1675960081|Dupli|12"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group1740918352|Dupli|46"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group1753917514|Dupli|5"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group1754683637|Dupli|40"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group1764140354|Dupli|60"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group1870575723|Dupli|65"].geometry}
          material={materials["mat16.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group1899843208|Dupli|36"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group1956214489|Dupli|14"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group196400395|Dupli|15"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group1976194690|Dupli|18"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group205302596|Dupli|31"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group2074153597|Dupli|20"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group2085389804|Dupli|57"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group2091112366|Dupli|59"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group2106755496|Dupli|4"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group2146178072|Dupli|38"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group252681800|Dupli|7"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group268332703|Dupli|44"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group287159489|Dupli|13"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group295085766|Dupli|9"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group311988427|Dupli|1"].geometry}
          material={materials["mat22.011"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group34220672|Dupli|34"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group384612072|Dupli|10"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group418912012|Dupli|30"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group42243725|Dupli|37"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group425587018|Dupli|"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group449779970|Dupli|3"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group45382983|Dupli|52"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group475225180|Dupli|41"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group573547017|Dupli|49"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group588539140|Dupli|47"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group601803475|Dupli|25"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group616518658|Dupli|56"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group687259746|Dupli|51"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group706802639|Dupli|17"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group729811280|Dupli|48"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group77921105|Dupli|42"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group790925258|Dupli|54"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group801095923|Dupli|29"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group806343109|Dupli|27"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group826580911|Dupli|24"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group873458270|Dupli|55"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group873558583|Dupli|62"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group877249531|Dupli|66"].geometry}
          material={materials["mat9.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group954813675|Dupli|16"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group96314515|Dupli|2"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group96968687|Dupli|43"].geometry}
          material={materials["mat21.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Keyboard|group993315105|Dupli|45"].geometry}
          material={materials["mat21.013"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mouse001.geometry}
        material={materials["Material.001"]}
        position={[1.542, 1.677, -3.143]}
        rotation={[-Math.PI / 2, 0, 0.448]}
        scale={18189.904}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mousepad001.geometry}
        material={materials.Mousepad}
        position={[1.53, 1.681, -3.136]}
        rotation={[-Math.PI / 2, 0, -1.575]}
        scale={[31.344, 38.156, 0.414]}
      />
      <group
        position={[0.941, 1.669, -4.51]}
        rotation={[-Math.PI / 2, 0, 3.138]}
        scale={235.824}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["Mug_With_Office_Tool|Mug_with_office_tools|Dupli|"].geometry
          }
          material={materials["Material.015"]}
          scale={100}
        />
      </group>
      <group
        position={[-0.991, 1.677, -3.814]}
        rotation={[-Math.PI / 2, 0, 0.281]}
        scale={5.638}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Notebook|Notebook_Cube041|Dupli|_1"].geometry}
          material={materials["FFEB3B.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Notebook|Notebook_Cube041|Dupli|_2"].geometry}
          material={materials["795548.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Notebook|Notebook_Cube041|Dupli|_3"].geometry}
          material={materials["F44336.006"]}
        />
      </group>
      <group
        position={[1.585, 1.677, -3.746]}
        rotation={[-Math.PI / 2, 0, 3.138]}
        scale={33.888}
      >
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Soda001|Soda|Dupli|_1"].geometry}
            material={materials["White.005"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Soda001|Soda|Dupli|_2"].geometry}
            material={materials["Red.002"]}
          />
        </group>
      </group>
      <group
        position={[-4.768, 3.139, -2.163]}
        rotation={[-Math.PI, 1.553, -Math.PI]}
        scale={196.892}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shelf_Clutter_1.geometry}
          material={materials.mat22}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shelf_Clutter_2.geometry}
          material={materials["4096"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shelf_Clutter_3.geometry}
          material={materials.mat15}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shelf_Clutter_4.geometry}
          material={materials.mat1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shelf_Clutter_5.geometry}
          material={materials.mat21}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shelf_Clutter_6.geometry}
          material={materials.mat11}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shelf_Clutter_7.geometry}
          material={materials.mat20}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shelf_Clutter_8.geometry}
          material={materials.mat16}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shelf_Clutter_9.geometry}
          material={materials.mat24}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shelf_Clutter_10.geometry}
          material={materials.mat8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shelf_Clutter_11.geometry}
          material={materials.mat23}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shelf_Clutter_12.geometry}
          material={materials.mat7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shelf_Clutter_13.geometry}
          material={materials.mat12}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shelf_Clutter_14.geometry}
          material={materials.mat4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shelf_Clutter_15.geometry}
          material={materials.mat10}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/CV_room1.gltf");
